package com.b1g.player.data.db

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Rows are keyed by an autogenerated id rather than the content id so that insertion
 * order is preserved and duplicate entries survive — a playlist is a document, and
 * two rows pointing at the same stream are still two rows in it.
 */
@Entity(
    tableName = "channels",
    indices = [
        Index("sourceId", "categoryId"),
        Index("sourceId", "name"),
    ],
)
data class ChannelEntity(
    @PrimaryKey(autoGenerate = true) val rowId: Long = 0,
    val sourceId: String,
    val contentId: String,
    val name: String,
    val logoUrl: String?,
    val categoryId: String?,
    val categoryName: String?,
    val epgChannelId: String?,
    val number: Int?,
    val streamUrl: String,
    /** Per-stream headers, as a JSON object. */
    val headersJson: String,
)

@Entity(
    tableName = "vod",
    indices = [
        Index("sourceId", "categoryId"),
        Index("sourceId", "name"),
    ],
)
data class VodEntity(
    @PrimaryKey(autoGenerate = true) val rowId: Long = 0,
    val sourceId: String,
    val contentId: String,
    val name: String,
    val logoUrl: String?,
    val categoryId: String?,
    val categoryName: String?,
    val rating: Double?,
    val addedEpochSeconds: Long?,
    val streamUrl: String,
    val headersJson: String,
)

/**
 * One episode of a series.
 *
 * The show's own details repeat on every row because that is how a playlist states
 * them — there is no series record to read — and the series list is a GROUP BY over
 * these rather than a second table that could drift out of step.
 */
@Entity(
    tableName = "episodes",
    indices = [
        Index("sourceId", "seriesId"),
        Index("sourceId", "categoryId"),
        Index("sourceId", "seriesName"),
    ],
)
data class EpisodeEntity(
    @PrimaryKey(autoGenerate = true) val rowId: Long = 0,
    val sourceId: String,
    val seriesId: String,
    val seriesName: String,
    val seriesCover: String?,
    val categoryId: String?,
    val categoryName: String?,
    val contentId: String,
    val seasonNumber: Int,
    val episodeNumber: Int,
    val title: String,
    val plot: String?,
    val durationSeconds: Int?,
    val stillUrl: String?,
    val streamUrl: String,
    val headersJson: String,
)

/** What is known about a stored playlist as a whole. */
@Entity(tableName = "source_meta")
data class SourceMetaEntity(
    @PrimaryKey val sourceId: String,
    val refreshedAt: Long,
    val epgUrl: String?,
)

/** Projection for the distinct category query. */
data class CategoryRow(
    val categoryId: String,
    val categoryName: String?,
)

/** Projection for the grouped series query. */
data class SeriesRow(
    val seriesId: String,
    // Nullable because they come from MIN() over the group, which Room treats as
    // possibly null even though a group always has rows.
    val seriesName: String?,
    val seriesCover: String?,
    val categoryId: String?,
    val categoryName: String?,
    val episodeCount: Int,
)
