package com.b1g.player.data.db

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Rows are keyed by an autogenerated id rather than the content id so that insertion
 * order is preserved and duplicate entries survive — a playlist is a document, and
 * two rows pointing at the same stream are still two rows in it.
 */
@Entity(
    tableName = "channels",
    indices = [
        Index("sourceId", "categoryId"),
        Index("sourceId", "name"),
    ],
)
data class ChannelEntity(
    @PrimaryKey(autoGenerate = true) val rowId: Long = 0,
    val sourceId: String,
    val contentId: String,
    val name: String,
    val logoUrl: String?,
    val categoryId: String?,
    val categoryName: String?,
    val epgChannelId: String?,
    val number: Int?,
    val streamUrl: String,
    /** Per-stream headers, as a JSON object. */
    val headersJson: String,
)

@Entity(
    tableName = "vod",
    indices = [
        Index("sourceId", "categoryId"),
        Index("sourceId", "name"),
    ],
)
data class VodEntity(
    @PrimaryKey(autoGenerate = true) val rowId: Long = 0,
    val sourceId: String,
    val contentId: String,
    val name: String,
    val logoUrl: String?,
    val categoryId: String?,
    val categoryName: String?,
    val rating: Double?,
    val addedEpochSeconds: Long?,
    val streamUrl: String,
    val headersJson: String,
)

/** What is known about a stored playlist as a whole. */
@Entity(tableName = "source_meta")
data class SourceMetaEntity(
    @PrimaryKey val sourceId: String,
    val refreshedAt: Long,
    val epgUrl: String?,
)

/** Projection for the distinct category query. */
data class CategoryRow(
    val categoryId: String,
    val categoryName: String?,
)
